name: Deploy Next.js App to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.hammzadev.me
          username: u625255424.hammzadev
          password: Ha@122121
          local-dir: out/ # This should match the output directory
          server-dir: /
          clean: true # This will delete existing files in the server-dir before deploying
